-- MySQL Script generated by MySQL Workbench
-- Fri Nov 13 02:02:59 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;


-- -----------------------------------------------------
-- Schema goceries
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `goceries` DEFAULT CHARACTER SET utf8mb4 ;
USE `goceries` ;

-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `users` (
  `user_ID` INT(10) NOT NULL,
  `user_email` VARCHAR(255) NOT NULL,
  `user_password` VARCHAR(255) NOT NULL,
  `user_firstname` VARCHAR(255) NOT NULL,
  -- `user_lastname` VARCHAR(255) NOT NULL,
  -- `user_address` VARCHAR(255) NOT NULL,
  -- `user_phone` INT(10) NOT NULL,
  `order_ID` INT(11),
  PRIMARY KEY (`user_ID`)
  -- CONSTRAINT FK_user_orders
  --   FOREIGN KEY (order_ID)
  --   REFERENCES `orders` (`order_ID`)
  --   ON DELETE NO ACTION
  --   ON UPDATE NO ACTION
  )

ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orders` (
  `order_ID` INT(11) NOT NULL,
  `user_ID` INT(10) NOT NULL,
  `order_total` INT(11) NOT NULL,
  `order_tax` INT(11) NOT NULL,
  `order_date` DATETIME NULL,
  `order_delivery_status` VARCHAR(45) NULL,
  PRIMARY KEY (`order_ID`)
  -- CONSTRAINT FK_person_who_ordered
  --   FOREIGN KEY (`user_ID`)
  --   REFERENCES `users` (`user_ID`)
  )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `products` (
  `product_ID` INT(3) NOT NULL,
  `product_name` VARCHAR(255) NOT NULL,
  `product_category` VARCHAR(45) NOT NULL,
  `product_price` DECIMAL(10,2) NOT NULL,
  `product_weight` DECIMAL(10,2) NOT NULL,
  `product_stock` INT(5) NOT NULL,
  `product_description` VARCHAR(2555) NOT NULL,
  `product_imagename` VARCHAR(255) NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `orders_products_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orders_products_details` (
  `order_product_details_ID` INT(11) NOT NULL,
  `order_ID` INT(11) NOT NULL,
  `product_ID` INT(3) NOT NULL,
  `order_product_totalweight` DECIMAL(10,2) NOT NULL,
  `order_product_totalquantity` INT NOT NULL,
  PRIMARY KEY (`order_product_details_ID`),
  CONSTRAINT FK_orderID
    FOREIGN KEY (`order_ID`)
    REFERENCES `orders` (`order_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
  -- CONSTRAINT FK_product_ID
  --   FOREIGN KEY (`product_ID`)
  --   REFERENCES `products` (`product_ID`).
  --   ON DELETE NO ACTION
  --   ON UPDATE NO ACTION
  )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;



-- ------------------------------------------------------
--    Dump products data to products table    
-- ------------------------------------------------------
INSERT INTO `products` (`product_ID`,`product_name`,`product_category`,`product_price`, `product_weight`, `product_stock`, 
`product_imagename`)

VALUES 
(101, 'Organic Gala Apple', 'fruits', 0.76 , 0.35 ,100, 'fruit-apple.jpg' ),
(102, 'Banana', 'fruits', 0.76 , 0.35, 100, 'fruit-apple.jpg' ),
(103, 'Blueberry', 'fruits', 0.76 , 0.35, 100, 'fruit-apple.jpg' ),
(104, 'Cantaloupe', 'fruits', 0.76 , 0.35, 100, 'fruit-apple.jpg' ),
(105, 'Peach', 'fruits', 0.76 , 0.35, 100, 'fruit-apple.jpg' ),
(106, 'Strawberry', 'fruits', 0.76 , 0.35, 100, 'fruit-apple.jpg' ),(201, 'Asparagus','vegetables', 0.76 , 0.35, 100, 'fruit-apple.jpg' ),
(202, 'Beans', 'vegetables', 0.76 , 0.35, 100, 'fruit-apple.jpg' ),
(203, 'Cabbage', 'vegetables', 0.76 , 0.35,100, 'fruit-apple.jpg' ),
(204, 'Carrot', 'vegetables', 0.76 , 0.35, 100, 'fruit-apple.jpg' ),
(205, 'Pepper', 'vegetables', 0.76 , 0.35, 100, 'fruit-apple.jpg' ),
(206, 'Tomato', 'vegetables', 0.76 , 0.35, 100, 'fruit-apple.jpg' ),(301, 'Creamer', 'Dairy & Eggs',0.76 , 0.35, 100, 'fruit-apple.jpg' ),
(302, 'Milk', 'Dairy & Eggs',0.76 , 0.35, 100, 'fruit-apple.jpg' ),
(303, 'Egg', 'Dairy & Eggs',0.76 , 0.35,100, 'fruit-apple.jpg' ),
(304, 'Oatmilk', 'Dairy & Eggs',0.76 , 0.35, 100, 'fruit-apple.jpg' ),
(305, 'eggland', 'Dairy & Eggs',0.76 , 0.35, 100, 'fruit-apple.jpg' ),
(306, 'yogurt', 'Dairy & Eggs',0.76 , 0.35, 100, 'fruit-apple.jpg' );
